### ISSUE TITLE
Handle a simple GET

### ISSUE THREAD

**Issue by stevenklassen8376** [klassen-software-solutions/crest#26]
This will accept a URL, perform a GET, and echo the response.

- [x] #1 The program will handle http
- [x] #22 Request headers (partial)
- [x] #8 HTTP methods (partial)
- [x] #25 Error handling
