### ISSUE TITLE
Add request headers and content

### ISSUE THREAD

**Issue by stevenklassen8376** [klassen-software-solutions/crest#29]
This will cover:

- [x] #22 small set of request headers
- [x] #8 standard HTTP methods
- [x] #20 request content
- [x] #21 auto-recognition of the request content
- [x] #28 large requests and responses efficiently
