### ISSUE TITLE
Add configuration

### ISSUE THREAD

**Issue by stevenklassen8376** [klassen-software-solutions/crest#31]
This will involve various configuration and overrides via a global configuration file, a local configuration file, and command line options. It will involve the following requirements:

- [x] #22 Automatically populate request headers (overrides)
- [x] #21 Automatically determine content type (overrides)
- [x] #3 Global configuration
- [x] #4 Local configuration
- [x] #5 Command line configuration
- [x] #18 Configure the request headers
- [x] #19 Command line request headers
- [x] #10 Common path prefix
