### ISSUE TITLE
add response support

### ISSUE THREAD

**Issue by stevenklassen8376** [klassen-software-solutions/crest#33]
This will include the following:

- [x] #11 display response headers
- [x] #12 pretty print responses
- [x] #13 handle binary data (show size)
- [x] #28 efficient handling of large response
